name: afon_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # locale
  klocalizations_flutter: ^0.0.4

  # architecture
  flutter_bloc: ^7.2.0
  get_it: ^6.0.0
  injectable: ^1.2.0
  form_bloc: ^0.20.1
  flutter_form_bloc: ^0.20.1

  # utils
  freezed_annotation: ^0.14.0
  cupertino_icons: ^1.0.2
  logger: ^1.1.0

  # network
  dio: ^4.0.4
  webview_flutter: ^3.0.0

  # image
  flutter_svg: ^1.0.1

  # ui
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.14.0+1
  build_runner: ^2.1.1
  injectable_generator: ^1.2.0
#  flutter_native_splash: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/png/

  fonts:
    - family: AsketNarrow
      fonts:
        - asset: fonts/Asket_Narrow_Light.ttf
    - family: RossikaLight
      fonts:
        - asset: fonts/Rossika_Light_Regular.ttf
    - family: EposNormalApp
      fonts:
        - asset: fonts/Epos-Normal-App.ttf
    - family: afon_icons
      fonts:
        - asset: fonts/afon_icons.ttf

# Для создания SplashScreen нужно выполнить: & flutter pub run flutter_native_splash:create
#flutter_native_splash:
#  color: "#D5D8CB"
#  branding: assets/png/splash.png
#  color_dark: "#D5D8CB"
#  branding_dark: assets/png/splash.png
#  android_gravity: fill_horizontal
#  ios_content_mode: scaleAspectFill
#  fullscreen: true
